### ISSUE TITLE
GraphQl 502 in docker on login

### ISSUE THREAD

**Issue by mattiasghodsian** [openpim/server#19]
Attempting to configure the Docker container and NGINX for proxying to the container. Upon logging into the website, GraphQL returns a 502 status, which is also reflected in the Docker container logs.

```
production_1  | 172.19.0.1 - - [18/Apr/2023:12:42:29 +0000] "GET /graphql HTTP/1.0" 502 575 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
production_1  | 2023/04/18 12:42:30 [error] 12#12: *388 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /graphql HTTP/1.0", upstream: "http://127.0.0.1:8080/graphql", host: "pim.mysitecom"
```
## Setup
docker-compose.yml
```yml
version: '3.3'
services:
    production:
        ports:
            - 88:80
        volumes:
          - ./config:/filestorage
        environment:
            - OPENPIM_DATABASE_ADDRESS=localhost
            - OPENPIM_DATABASE_NAME=
            - OPENPIM_DATABASE_USER=
            - OPENPIM_DATABASE_PASSWORD=
        image: 'openpim/production:1.5'
        restart: unless-stopped

```
nginx
```
server {
    listen 80;
    server_name pim.mysite.com;

    location / {
        proxy_pass http://localhost:88;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

```

![image](https://user-images.githubusercontent.com/20265517/232785380-655ed6d0-dee2-41e4-a6ec-40e0f6bd9b3a.png)

**Comment by openpim** [comment]
@mattiasghodsian 

Docker container is like a virtual machine, so if you have your host with DB with some IP address (for example 10.1.1.1) and you have a docker container running on it. So your DB address is 10.1.1.1 and not a localhost from the docker container point of view.

**Comment by openpim** [comment]
can you please take a look what you have in the server log? You should see the error and then it will be clear what is the reason.

You can see it in the docker log or you can go directly to the server.
You should make the following to see them:

1. Execute command "sudo docker container ls" and you will see all started docker processes (if you have only our system inside docker you will see only one process). And you should copy <container id>

2. Execute command "sudo docker exec -it <container id> /bin/bash". So you will go inside docker virtual machine and you will see the command prompt

3. Execute "cat server.log". I think you will see an error that the system can not connect to the database in the error log.

**Comment by mattiasghodsian** [comment]
I have decided to transition from hosting PostgreSQL directly on the server to utilizing a containerized approach. This change has been successfully implemented and is now fully operational.

```yml
version: '3.3'
services:
    production:
        image: 'openpim/production:1.5'
        depends_on:
          - db
        ports:
          - 88:80
        volumes:
          - ./config:/filestorage
        environment:
          - OPENPIM_DATABASE_ADDRESS=db
          - OPENPIM_DATABASE_NAME=test
          - OPENPIM_DATABASE_USER=test
          - OPENPIM_DATABASE_PASSWORD=test
        restart: unless-stopped
    db:
      image: postgres
      volumes:
        - ./postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=test
        - POSTGRES_USER=openpim
        - POSTGRES_PASSWORD=test
      restart: always
```
