### ISSUE TITLE
Bad Gateway (502) running openpim/production:1.5 

### ISSUE THREAD

**Issue by killertilapia** [openpim/server#21]
Trying to run OpenPIM/Production:1.5 using `docker compose` locally and I keep getting a 502 error when trying to login.

```bash
2023-06-21 13:41:27 2023/06/21 05:41:27 [error] 16#16: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: _, request: "POST /graphql HTTP/1.1", upstream: "http://127.0.0.1:8080/graphql", host: "localhost", referrer: "http://localhost/"

2023-06-21 13:41:27 172.24.0.1 - - [21/Jun/2023:05:41:27 +0000] "POST /graphql HTTP/1.1" 502 575 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
```

The docker-compose file is nothing special considering that #19 looks to be solved.

```yml
version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=dba2
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgadmin4-data:/var/lib/pgadmin

  openpim:
    image: openpim/production:1.5
    volumes:
      - ./filestorage:/filestorage
    environment:
      - OPENPIM_DATABASE_ADDRESS=postgres
      - OPENPIM_DATABASE_NAME=dba2
      - OPENPIM_DATABASE_USER=postgres
      - OPENPIM_DATABASE_PASSWORD=sa
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 80:80
  
  pgadmin:
    image: dpage/pgadmin4:6.5
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@test.org
      - PGADMIN_DEFAULT_PASSWORD=sa

volumes:
  pgadmin4-data:
```
