### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by vvmalkov** [openpim/server#25]
docker compose запустился локально только с измененным yaml файлом.
```
version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  openpim:
    image: openpim/production:1.3
    environment:
      OPENPIM_DATABASE_ADDRESS: postgres
      OPENPIM_DATABASE_PASSWORD: sa
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 80:80
  
  pgadmin:
    image: dpage/pgadmin4:6.5
    restart: always
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  pgadmin-data:

```
